### ISSUE TITLE
Testing feedback

### ISSUE THREAD

**Issue by LinusMelb** [CS2103AUG2017-W13-B4/main#253]
Bad things:
1. The modules in the list are not clickable. The only way to check timetable is typing view INDEX, which is not user-friendly.

2. When the user is viewing one module, the user cannot switch to other modules by using view command. The only way to check other modules' timetable is to list all modules again and then type the module you'd like to view.

![image](https://user-images.githubusercontent.com/17083284/32363123-9df07f68-c0a8-11e7-8b40-50b0d6ec4035.png)

![image](https://user-images.githubusercontent.com/17083284/32363147-c2b25a06-c0a8-11e7-8aa4-06eb943df7b1.png)

Instead, it will give the incorrect feedback that this is an invalid index.

Good things:
1. The whole design is good, consistent and neat.
2. User can change themes based on their taste
3. User also can change font-size and there are many options to choose

**Comment by caoliangnus** [comment]
Hi, the main input for ModU should be CLI as per the project requirement

**Comment by junming403** [comment]
Hi thanks for your feedback, but may i know how is the ` invalid index` happens in a little bit more detail thus I can targeting the error.
