### ISSUE TITLE
Suggestions and User Guide Tutorial Issues

### ISSUE THREAD

**Issue by jvossy** [CS2103AUG2017-W13-B4/main#254]
First thing I noticed in the user guide it it looks like it has giant pictures and none of them show up.
-The calendar type view that seems to be the most important part is surprisingly hard to get to, I feel like it should open automatically and show marked modules on it, and not vanish whenever another command is run.
-When I enter commands with color enable active, some weird yellow text makes it really hard to read anything I'm typing.
-Modules displayed in list only show their name, which makes them nearly useless. It seems like you have to view one before you can see anything useful, and when you do the box is the same size anyway. Just make it part of the list view.
-The command I was told to enter: 'add CS2101 ct/LEC v/LT27 gp/1 ts/FRI[1400-1600] l/ Ma Siu Lun' failed. When I corrected the extra space in '...l/ Ma...' and added a 'm/' in front of the module, it worked.
-user guide references 'In addition, you can continue adding MA1101R lessons in the command box and it will reflect on the timetable instantaneously' but does not describe how to do that. Edit does not do this, it replaces the time slot. Add adds a whole new module, which seems wrong. It feels unnatural to have to add all the details again to just add a new time slot for a class, especially because then when you edit the details of one, the other gets totally disconnected.
-Typing 'edit 1 MA1010' as the user guide instructs does not work. fixing it to '..m/..' does.
-typing 'find CS2101' does not work, gives an error. Maybe I accidentally edited this module in the previous step?
-subsequently, view 1 does not work.
-Even if i type 'find MA1010', the file I just made, I get 'find command executed' but the list remains white and shows nothing.

Otherwise, the user guide is well written and easy to follow. I'm confident the issues with the commands it says to enter are ultimately just typos. The only potential bug I think I ran into was that 'find CS2101' said it executed but did not find anything. Perhaps it was searching the current list, which is already empty? If that's the case, I'd like it to say 'found nothing'. Especially when running it again, when all I see is an empty screen and I have no idea what list it's actually searching, it'd be nice to get some feedback.

**Comment by angtianlannus** [comment]
Thank you for your feedback, may I ask when you execute find command, is the list panel showing a list of module names?
